# Generated by Django 4.2.5 on 2024-03-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
